---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: golang-builder-{{ include "go-webapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "go-webapp.name" . }}
    helm.sh/chart: {{ include "go-webapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  runPolicy: Serial
  triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: "base-centos7:latest"
  source:
    git:
      uri: "https://github.com/ycornamusaz/s2i-golang-builder.git"
    type: Git
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: golang-builder-{{ template "go-webapp.fullname" . }}:latest
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: go-webapp-{{ include "go-webapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "go-webapp.name" . }}
    helm.sh/chart: {{ include "go-webapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  runPolicy: Serial
  triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: golang-builder-{{ template "go-webapp.fullname" . }}:latest
    - type: GitHub
      github:
        secret: {{ .Values.github_webhook | quote }}
  source:
    git:
      uri: "https://github.com/ycornamusaz/go-webapp.git"
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: golang-builder-{{ template "go-webapp.fullname" . }}:latest
  output:
    to:
      kind: ImageStreamTag
      name: go-webapp-{{ template "go-webapp.fullname" . }}:latest
