---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-webapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "go-webapp.name" . }}
    helm.sh/chart: {{ include "go-webapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  github_webhook: {{ .Values.github_webhook }}
